export const SPECIALTIES = [
  "Internal Medicine",
  "Urology",
  "Dermatology",
  "Oncology",
  "Pulmonology",
  "Pathology",
  "Thoracic Surgery",
  "General Surgery",
  "Neurosurgery",
  "Dental Billing",
  "Family Practice",
  "Molecular Labs",
  "Podiatry",
  "Cardiology",
  "Rheumatology",
  "Endocrinology",
  "Physical Therapy",
  "Psychiatric",
  "Psychology",
  "OB/GYN",
  "Wound Care",
  "Census Entry",
  "Home Health",
  "Radiology",
  "Medical Clinics",
  "Hematology",
  "Nursing Home",
  "Infectious Disease",
  "Pediatric",
  "Traumatology",
  "Disability Services",
  "Prostheses",
  "FQHC",
  "Clinical Lab",
  "Hospice",
  "Toxicology",
  "Ophthalmology",
  "Geriatrics",
  "Gastroenterology",
  "Hepatology",
  "Nephrology",
  "Immunology",
  "Durable Medical Equipment",
  "Substance Abuse Rehab",
  "Pain Management",
  "Mental Health",
  "Urgent Care",
  "Ambulatory Surgery",
  "Orthopedic",
] as const;

export type Specialty = (typeof SPECIALTIES)[number];
